#!/bin/bash

TARGET=${1:-""}

source ./_source

if [[ $TARGET != "" ]]; then
    ANSWER=$(python python_scripts/get_entry.py --target=$TARGET)
    
    if [[ $ANSWER == "None" ]]; then
        echo "No such target found"
        exit 1
    fi

    USERNAME=$(echo $ANSWER | cut -d' ' -f 1)
    IP=$(echo $ANSWER | cut -d' ' -f 2)
    PASSWORD=$(echo $ANSWER | cut -d' ' -f 3)
    PORT=$(echo $ANSWER | cut -d' ' -f 4)
    ISPEM=$(echo $ANSWER | cut -d' ' -f 5)
    
    if [[ $ISPEM == "True" ]]; then
        ssh -i $PASSWORD $USERNAME@$IP -p $PORT
        exit 0
    fi
    
    sshpass -p $PASSWORD ssh $USERNAME@$IP -p $PORT
else
    echo "Please specify target to connect to"
fi